#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLiLaoDong")]
	public partial class QLLD_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChamCong(ChamCong instance);
    partial void UpdateChamCong(ChamCong instance);
    partial void DeleteChamCong(ChamCong instance);
    partial void InsertChamCong_PDA(ChamCong_PDA instance);
    partial void UpdateChamCong_PDA(ChamCong_PDA instance);
    partial void DeleteChamCong_PDA(ChamCong_PDA instance);
    partial void InsertCongTrinh(CongTrinh instance);
    partial void UpdateCongTrinh(CongTrinh instance);
    partial void DeleteCongTrinh(CongTrinh instance);
    partial void InsertLienHe(LienHe instance);
    partial void UpdateLienHe(LienHe instance);
    partial void DeleteLienHe(LienHe instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhanCong(PhanCong instance);
    partial void UpdatePhanCong(PhanCong instance);
    partial void DeletePhanCong(PhanCong instance);
    partial void InsertPhongBan(PhongBan instance);
    partial void UpdatePhongBan(PhongBan instance);
    partial void DeletePhongBan(PhongBan instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public QLLD_DBDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLiLaoDongConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLLD_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLD_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLD_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLLD_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChamCong> ChamCongs
		{
			get
			{
				return this.GetTable<ChamCong>();
			}
		}
		
		public System.Data.Linq.Table<ChamCong_PDA> ChamCong_PDAs
		{
			get
			{
				return this.GetTable<ChamCong_PDA>();
			}
		}
		
		public System.Data.Linq.Table<CongTrinh> CongTrinhs
		{
			get
			{
				return this.GetTable<CongTrinh>();
			}
		}
		
		public System.Data.Linq.Table<LienHe> LienHes
		{
			get
			{
				return this.GetTable<LienHe>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhanCong> PhanCongs
		{
			get
			{
				return this.GetTable<PhanCong>();
			}
		}
		
		public System.Data.Linq.Table<PhongBan> PhongBans
		{
			get
			{
				return this.GetTable<PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChamCong")]
	public partial class ChamCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChamCong;
		
		private System.Nullable<int> _maPhanCong;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _nam;
		
		private System.Nullable<int> _soNgayLam;
		
		private System.Nullable<int> _soNgayNghi;
		
		private System.Nullable<decimal> _luongThang;
		
		private string _D1;
		
		private string _D2;
		
		private string _D3;
		
		private string _D4;
		
		private string _D5;
		
		private string _D6;
		
		private string _D7;
		
		private string _D8;
		
		private string _D9;
		
		private string _D10;
		
		private string _D11;
		
		private string _D12;
		
		private string _D13;
		
		private string _D14;
		
		private string _D15;
		
		private string _D16;
		
		private string _D17;
		
		private string _D18;
		
		private string _D19;
		
		private string _D20;
		
		private string _D21;
		
		private string _D22;
		
		private string _D23;
		
		private string _D24;
		
		private string _D25;
		
		private string _D26;
		
		private string _D27;
		
		private string _D28;
		
		private string _D29;
		
		private string _D30;
		
		private string _D31;
		
		private EntityRef<PhanCong> _PhanCong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChamCongChanging(int value);
    partial void OnmaChamCongChanged();
    partial void OnmaPhanCongChanging(System.Nullable<int> value);
    partial void OnmaPhanCongChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void OnsoNgayLamChanging(System.Nullable<int> value);
    partial void OnsoNgayLamChanged();
    partial void OnsoNgayNghiChanging(System.Nullable<int> value);
    partial void OnsoNgayNghiChanged();
    partial void OnluongThangChanging(System.Nullable<decimal> value);
    partial void OnluongThangChanged();
    partial void OnD1Changing(string value);
    partial void OnD1Changed();
    partial void OnD2Changing(string value);
    partial void OnD2Changed();
    partial void OnD3Changing(string value);
    partial void OnD3Changed();
    partial void OnD4Changing(string value);
    partial void OnD4Changed();
    partial void OnD5Changing(string value);
    partial void OnD5Changed();
    partial void OnD6Changing(string value);
    partial void OnD6Changed();
    partial void OnD7Changing(string value);
    partial void OnD7Changed();
    partial void OnD8Changing(string value);
    partial void OnD8Changed();
    partial void OnD9Changing(string value);
    partial void OnD9Changed();
    partial void OnD10Changing(string value);
    partial void OnD10Changed();
    partial void OnD11Changing(string value);
    partial void OnD11Changed();
    partial void OnD12Changing(string value);
    partial void OnD12Changed();
    partial void OnD13Changing(string value);
    partial void OnD13Changed();
    partial void OnD14Changing(string value);
    partial void OnD14Changed();
    partial void OnD15Changing(string value);
    partial void OnD15Changed();
    partial void OnD16Changing(string value);
    partial void OnD16Changed();
    partial void OnD17Changing(string value);
    partial void OnD17Changed();
    partial void OnD18Changing(string value);
    partial void OnD18Changed();
    partial void OnD19Changing(string value);
    partial void OnD19Changed();
    partial void OnD20Changing(string value);
    partial void OnD20Changed();
    partial void OnD21Changing(string value);
    partial void OnD21Changed();
    partial void OnD22Changing(string value);
    partial void OnD22Changed();
    partial void OnD23Changing(string value);
    partial void OnD23Changed();
    partial void OnD24Changing(string value);
    partial void OnD24Changed();
    partial void OnD25Changing(string value);
    partial void OnD25Changed();
    partial void OnD26Changing(string value);
    partial void OnD26Changed();
    partial void OnD27Changing(string value);
    partial void OnD27Changed();
    partial void OnD28Changing(string value);
    partial void OnD28Changed();
    partial void OnD29Changing(string value);
    partial void OnD29Changed();
    partial void OnD30Changing(string value);
    partial void OnD30Changed();
    partial void OnD31Changing(string value);
    partial void OnD31Changed();
    #endregion
		
		public ChamCong()
		{
			this._PhanCong = default(EntityRef<PhanCong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChamCong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maChamCong
		{
			get
			{
				return this._maChamCong;
			}
			set
			{
				if ((this._maChamCong != value))
				{
					this.OnmaChamCongChanging(value);
					this.SendPropertyChanging();
					this._maChamCong = value;
					this.SendPropertyChanged("maChamCong");
					this.OnmaChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhanCong", DbType="Int")]
		public System.Nullable<int> maPhanCong
		{
			get
			{
				return this._maPhanCong;
			}
			set
			{
				if ((this._maPhanCong != value))
				{
					if (this._PhanCong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhanCongChanging(value);
					this.SendPropertyChanging();
					this._maPhanCong = value;
					this.SendPropertyChanged("maPhanCong");
					this.OnmaPhanCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayLam", DbType="Int")]
		public System.Nullable<int> soNgayLam
		{
			get
			{
				return this._soNgayLam;
			}
			set
			{
				if ((this._soNgayLam != value))
				{
					this.OnsoNgayLamChanging(value);
					this.SendPropertyChanging();
					this._soNgayLam = value;
					this.SendPropertyChanged("soNgayLam");
					this.OnsoNgayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayNghi", DbType="Int")]
		public System.Nullable<int> soNgayNghi
		{
			get
			{
				return this._soNgayNghi;
			}
			set
			{
				if ((this._soNgayNghi != value))
				{
					this.OnsoNgayNghiChanging(value);
					this.SendPropertyChanging();
					this._soNgayNghi = value;
					this.SendPropertyChanged("soNgayNghi");
					this.OnsoNgayNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongThang", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> luongThang
		{
			get
			{
				return this._luongThang;
			}
			set
			{
				if ((this._luongThang != value))
				{
					this.OnluongThangChanging(value);
					this.SendPropertyChanging();
					this._luongThang = value;
					this.SendPropertyChanged("luongThang");
					this.OnluongThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D1", DbType="NVarChar(50)")]
		public string D1
		{
			get
			{
				return this._D1;
			}
			set
			{
				if ((this._D1 != value))
				{
					this.OnD1Changing(value);
					this.SendPropertyChanging();
					this._D1 = value;
					this.SendPropertyChanged("D1");
					this.OnD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D2", DbType="NVarChar(50)")]
		public string D2
		{
			get
			{
				return this._D2;
			}
			set
			{
				if ((this._D2 != value))
				{
					this.OnD2Changing(value);
					this.SendPropertyChanging();
					this._D2 = value;
					this.SendPropertyChanged("D2");
					this.OnD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D3", DbType="NVarChar(50)")]
		public string D3
		{
			get
			{
				return this._D3;
			}
			set
			{
				if ((this._D3 != value))
				{
					this.OnD3Changing(value);
					this.SendPropertyChanging();
					this._D3 = value;
					this.SendPropertyChanged("D3");
					this.OnD3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D4", DbType="NVarChar(50)")]
		public string D4
		{
			get
			{
				return this._D4;
			}
			set
			{
				if ((this._D4 != value))
				{
					this.OnD4Changing(value);
					this.SendPropertyChanging();
					this._D4 = value;
					this.SendPropertyChanged("D4");
					this.OnD4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D5", DbType="NVarChar(50)")]
		public string D5
		{
			get
			{
				return this._D5;
			}
			set
			{
				if ((this._D5 != value))
				{
					this.OnD5Changing(value);
					this.SendPropertyChanging();
					this._D5 = value;
					this.SendPropertyChanged("D5");
					this.OnD5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D6", DbType="NVarChar(50)")]
		public string D6
		{
			get
			{
				return this._D6;
			}
			set
			{
				if ((this._D6 != value))
				{
					this.OnD6Changing(value);
					this.SendPropertyChanging();
					this._D6 = value;
					this.SendPropertyChanged("D6");
					this.OnD6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D7", DbType="NVarChar(50)")]
		public string D7
		{
			get
			{
				return this._D7;
			}
			set
			{
				if ((this._D7 != value))
				{
					this.OnD7Changing(value);
					this.SendPropertyChanging();
					this._D7 = value;
					this.SendPropertyChanged("D7");
					this.OnD7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D8", DbType="NVarChar(50)")]
		public string D8
		{
			get
			{
				return this._D8;
			}
			set
			{
				if ((this._D8 != value))
				{
					this.OnD8Changing(value);
					this.SendPropertyChanging();
					this._D8 = value;
					this.SendPropertyChanged("D8");
					this.OnD8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D9", DbType="NVarChar(50)")]
		public string D9
		{
			get
			{
				return this._D9;
			}
			set
			{
				if ((this._D9 != value))
				{
					this.OnD9Changing(value);
					this.SendPropertyChanging();
					this._D9 = value;
					this.SendPropertyChanged("D9");
					this.OnD9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D10", DbType="NVarChar(50)")]
		public string D10
		{
			get
			{
				return this._D10;
			}
			set
			{
				if ((this._D10 != value))
				{
					this.OnD10Changing(value);
					this.SendPropertyChanging();
					this._D10 = value;
					this.SendPropertyChanged("D10");
					this.OnD10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D11", DbType="NVarChar(50)")]
		public string D11
		{
			get
			{
				return this._D11;
			}
			set
			{
				if ((this._D11 != value))
				{
					this.OnD11Changing(value);
					this.SendPropertyChanging();
					this._D11 = value;
					this.SendPropertyChanged("D11");
					this.OnD11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D12", DbType="NVarChar(50)")]
		public string D12
		{
			get
			{
				return this._D12;
			}
			set
			{
				if ((this._D12 != value))
				{
					this.OnD12Changing(value);
					this.SendPropertyChanging();
					this._D12 = value;
					this.SendPropertyChanged("D12");
					this.OnD12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D13", DbType="NVarChar(50)")]
		public string D13
		{
			get
			{
				return this._D13;
			}
			set
			{
				if ((this._D13 != value))
				{
					this.OnD13Changing(value);
					this.SendPropertyChanging();
					this._D13 = value;
					this.SendPropertyChanged("D13");
					this.OnD13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D14", DbType="NVarChar(50)")]
		public string D14
		{
			get
			{
				return this._D14;
			}
			set
			{
				if ((this._D14 != value))
				{
					this.OnD14Changing(value);
					this.SendPropertyChanging();
					this._D14 = value;
					this.SendPropertyChanged("D14");
					this.OnD14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D15", DbType="NVarChar(50)")]
		public string D15
		{
			get
			{
				return this._D15;
			}
			set
			{
				if ((this._D15 != value))
				{
					this.OnD15Changing(value);
					this.SendPropertyChanging();
					this._D15 = value;
					this.SendPropertyChanged("D15");
					this.OnD15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D16", DbType="NVarChar(50)")]
		public string D16
		{
			get
			{
				return this._D16;
			}
			set
			{
				if ((this._D16 != value))
				{
					this.OnD16Changing(value);
					this.SendPropertyChanging();
					this._D16 = value;
					this.SendPropertyChanged("D16");
					this.OnD16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D17", DbType="NVarChar(50)")]
		public string D17
		{
			get
			{
				return this._D17;
			}
			set
			{
				if ((this._D17 != value))
				{
					this.OnD17Changing(value);
					this.SendPropertyChanging();
					this._D17 = value;
					this.SendPropertyChanged("D17");
					this.OnD17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D18", DbType="NVarChar(50)")]
		public string D18
		{
			get
			{
				return this._D18;
			}
			set
			{
				if ((this._D18 != value))
				{
					this.OnD18Changing(value);
					this.SendPropertyChanging();
					this._D18 = value;
					this.SendPropertyChanged("D18");
					this.OnD18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D19", DbType="NVarChar(50)")]
		public string D19
		{
			get
			{
				return this._D19;
			}
			set
			{
				if ((this._D19 != value))
				{
					this.OnD19Changing(value);
					this.SendPropertyChanging();
					this._D19 = value;
					this.SendPropertyChanged("D19");
					this.OnD19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D20", DbType="NVarChar(50)")]
		public string D20
		{
			get
			{
				return this._D20;
			}
			set
			{
				if ((this._D20 != value))
				{
					this.OnD20Changing(value);
					this.SendPropertyChanging();
					this._D20 = value;
					this.SendPropertyChanged("D20");
					this.OnD20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D21", DbType="NVarChar(50)")]
		public string D21
		{
			get
			{
				return this._D21;
			}
			set
			{
				if ((this._D21 != value))
				{
					this.OnD21Changing(value);
					this.SendPropertyChanging();
					this._D21 = value;
					this.SendPropertyChanged("D21");
					this.OnD21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D22", DbType="NVarChar(50)")]
		public string D22
		{
			get
			{
				return this._D22;
			}
			set
			{
				if ((this._D22 != value))
				{
					this.OnD22Changing(value);
					this.SendPropertyChanging();
					this._D22 = value;
					this.SendPropertyChanged("D22");
					this.OnD22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D23", DbType="NVarChar(50)")]
		public string D23
		{
			get
			{
				return this._D23;
			}
			set
			{
				if ((this._D23 != value))
				{
					this.OnD23Changing(value);
					this.SendPropertyChanging();
					this._D23 = value;
					this.SendPropertyChanged("D23");
					this.OnD23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D24", DbType="NVarChar(50)")]
		public string D24
		{
			get
			{
				return this._D24;
			}
			set
			{
				if ((this._D24 != value))
				{
					this.OnD24Changing(value);
					this.SendPropertyChanging();
					this._D24 = value;
					this.SendPropertyChanged("D24");
					this.OnD24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D25", DbType="NVarChar(50)")]
		public string D25
		{
			get
			{
				return this._D25;
			}
			set
			{
				if ((this._D25 != value))
				{
					this.OnD25Changing(value);
					this.SendPropertyChanging();
					this._D25 = value;
					this.SendPropertyChanged("D25");
					this.OnD25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D26", DbType="NVarChar(50)")]
		public string D26
		{
			get
			{
				return this._D26;
			}
			set
			{
				if ((this._D26 != value))
				{
					this.OnD26Changing(value);
					this.SendPropertyChanging();
					this._D26 = value;
					this.SendPropertyChanged("D26");
					this.OnD26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D27", DbType="NVarChar(50)")]
		public string D27
		{
			get
			{
				return this._D27;
			}
			set
			{
				if ((this._D27 != value))
				{
					this.OnD27Changing(value);
					this.SendPropertyChanging();
					this._D27 = value;
					this.SendPropertyChanged("D27");
					this.OnD27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D28", DbType="NVarChar(50)")]
		public string D28
		{
			get
			{
				return this._D28;
			}
			set
			{
				if ((this._D28 != value))
				{
					this.OnD28Changing(value);
					this.SendPropertyChanging();
					this._D28 = value;
					this.SendPropertyChanged("D28");
					this.OnD28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D29", DbType="NVarChar(50)")]
		public string D29
		{
			get
			{
				return this._D29;
			}
			set
			{
				if ((this._D29 != value))
				{
					this.OnD29Changing(value);
					this.SendPropertyChanging();
					this._D29 = value;
					this.SendPropertyChanged("D29");
					this.OnD29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D30", DbType="NVarChar(50)")]
		public string D30
		{
			get
			{
				return this._D30;
			}
			set
			{
				if ((this._D30 != value))
				{
					this.OnD30Changing(value);
					this.SendPropertyChanging();
					this._D30 = value;
					this.SendPropertyChanged("D30");
					this.OnD30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D31", DbType="NVarChar(50)")]
		public string D31
		{
			get
			{
				return this._D31;
			}
			set
			{
				if ((this._D31 != value))
				{
					this.OnD31Changing(value);
					this.SendPropertyChanging();
					this._D31 = value;
					this.SendPropertyChanged("D31");
					this.OnD31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanCong_ChamCong", Storage="_PhanCong", ThisKey="maPhanCong", OtherKey="maPhanCong", IsForeignKey=true)]
		public PhanCong PhanCong
		{
			get
			{
				return this._PhanCong.Entity;
			}
			set
			{
				PhanCong previousValue = this._PhanCong.Entity;
				if (((previousValue != value) 
							|| (this._PhanCong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhanCong.Entity = null;
						previousValue.ChamCongs.Remove(this);
					}
					this._PhanCong.Entity = value;
					if ((value != null))
					{
						value.ChamCongs.Add(this);
						this._maPhanCong = value.maPhanCong;
					}
					else
					{
						this._maPhanCong = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhanCong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChamCong_PDA")]
	public partial class ChamCong_PDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChamCong;
		
		private string _maNhanVien;
		
		private System.Nullable<int> _thang;
		
		private System.Nullable<int> _nam;
		
		private System.Nullable<int> _soNgayLam;
		
		private System.Nullable<int> _soNgayNghi;
		
		private System.Nullable<decimal> _luongThang;
		
		private string _daTraLuong;
		
		private string _D1;
		
		private string _D2;
		
		private string _D3;
		
		private string _D4;
		
		private string _D5;
		
		private string _D6;
		
		private string _D7;
		
		private string _D8;
		
		private string _D9;
		
		private string _D10;
		
		private string _D11;
		
		private string _D12;
		
		private string _D13;
		
		private string _D14;
		
		private string _D15;
		
		private string _D16;
		
		private string _D17;
		
		private string _D18;
		
		private string _D19;
		
		private string _D20;
		
		private string _D21;
		
		private string _D22;
		
		private string _D23;
		
		private string _D24;
		
		private string _D25;
		
		private string _D26;
		
		private string _D27;
		
		private string _D28;
		
		private string _D29;
		
		private string _D30;
		
		private string _D31;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChamCongChanging(int value);
    partial void OnmaChamCongChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnthangChanging(System.Nullable<int> value);
    partial void OnthangChanged();
    partial void OnnamChanging(System.Nullable<int> value);
    partial void OnnamChanged();
    partial void OnsoNgayLamChanging(System.Nullable<int> value);
    partial void OnsoNgayLamChanged();
    partial void OnsoNgayNghiChanging(System.Nullable<int> value);
    partial void OnsoNgayNghiChanged();
    partial void OnluongThangChanging(System.Nullable<decimal> value);
    partial void OnluongThangChanged();
    partial void OndaTraLuongChanging(string value);
    partial void OndaTraLuongChanged();
    partial void OnD1Changing(string value);
    partial void OnD1Changed();
    partial void OnD2Changing(string value);
    partial void OnD2Changed();
    partial void OnD3Changing(string value);
    partial void OnD3Changed();
    partial void OnD4Changing(string value);
    partial void OnD4Changed();
    partial void OnD5Changing(string value);
    partial void OnD5Changed();
    partial void OnD6Changing(string value);
    partial void OnD6Changed();
    partial void OnD7Changing(string value);
    partial void OnD7Changed();
    partial void OnD8Changing(string value);
    partial void OnD8Changed();
    partial void OnD9Changing(string value);
    partial void OnD9Changed();
    partial void OnD10Changing(string value);
    partial void OnD10Changed();
    partial void OnD11Changing(string value);
    partial void OnD11Changed();
    partial void OnD12Changing(string value);
    partial void OnD12Changed();
    partial void OnD13Changing(string value);
    partial void OnD13Changed();
    partial void OnD14Changing(string value);
    partial void OnD14Changed();
    partial void OnD15Changing(string value);
    partial void OnD15Changed();
    partial void OnD16Changing(string value);
    partial void OnD16Changed();
    partial void OnD17Changing(string value);
    partial void OnD17Changed();
    partial void OnD18Changing(string value);
    partial void OnD18Changed();
    partial void OnD19Changing(string value);
    partial void OnD19Changed();
    partial void OnD20Changing(string value);
    partial void OnD20Changed();
    partial void OnD21Changing(string value);
    partial void OnD21Changed();
    partial void OnD22Changing(string value);
    partial void OnD22Changed();
    partial void OnD23Changing(string value);
    partial void OnD23Changed();
    partial void OnD24Changing(string value);
    partial void OnD24Changed();
    partial void OnD25Changing(string value);
    partial void OnD25Changed();
    partial void OnD26Changing(string value);
    partial void OnD26Changed();
    partial void OnD27Changing(string value);
    partial void OnD27Changed();
    partial void OnD28Changing(string value);
    partial void OnD28Changed();
    partial void OnD29Changing(string value);
    partial void OnD29Changed();
    partial void OnD30Changing(string value);
    partial void OnD30Changed();
    partial void OnD31Changing(string value);
    partial void OnD31Changed();
    #endregion
		
		public ChamCong_PDA()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChamCong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maChamCong
		{
			get
			{
				return this._maChamCong;
			}
			set
			{
				if ((this._maChamCong != value))
				{
					this.OnmaChamCongChanging(value);
					this.SendPropertyChanging();
					this._maChamCong = value;
					this.SendPropertyChanged("maChamCong");
					this.OnmaChamCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="Int")]
		public System.Nullable<int> thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="Int")]
		public System.Nullable<int> nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayLam", DbType="Int")]
		public System.Nullable<int> soNgayLam
		{
			get
			{
				return this._soNgayLam;
			}
			set
			{
				if ((this._soNgayLam != value))
				{
					this.OnsoNgayLamChanging(value);
					this.SendPropertyChanging();
					this._soNgayLam = value;
					this.SendPropertyChanged("soNgayLam");
					this.OnsoNgayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayNghi", DbType="Int")]
		public System.Nullable<int> soNgayNghi
		{
			get
			{
				return this._soNgayNghi;
			}
			set
			{
				if ((this._soNgayNghi != value))
				{
					this.OnsoNgayNghiChanging(value);
					this.SendPropertyChanging();
					this._soNgayNghi = value;
					this.SendPropertyChanged("soNgayNghi");
					this.OnsoNgayNghiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongThang", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> luongThang
		{
			get
			{
				return this._luongThang;
			}
			set
			{
				if ((this._luongThang != value))
				{
					this.OnluongThangChanging(value);
					this.SendPropertyChanging();
					this._luongThang = value;
					this.SendPropertyChanged("luongThang");
					this.OnluongThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daTraLuong", DbType="NVarChar(50)")]
		public string daTraLuong
		{
			get
			{
				return this._daTraLuong;
			}
			set
			{
				if ((this._daTraLuong != value))
				{
					this.OndaTraLuongChanging(value);
					this.SendPropertyChanging();
					this._daTraLuong = value;
					this.SendPropertyChanged("daTraLuong");
					this.OndaTraLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D1", DbType="NVarChar(50)")]
		public string D1
		{
			get
			{
				return this._D1;
			}
			set
			{
				if ((this._D1 != value))
				{
					this.OnD1Changing(value);
					this.SendPropertyChanging();
					this._D1 = value;
					this.SendPropertyChanged("D1");
					this.OnD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D2", DbType="NVarChar(10)")]
		public string D2
		{
			get
			{
				return this._D2;
			}
			set
			{
				if ((this._D2 != value))
				{
					this.OnD2Changing(value);
					this.SendPropertyChanging();
					this._D2 = value;
					this.SendPropertyChanged("D2");
					this.OnD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D3", DbType="NVarChar(10)")]
		public string D3
		{
			get
			{
				return this._D3;
			}
			set
			{
				if ((this._D3 != value))
				{
					this.OnD3Changing(value);
					this.SendPropertyChanging();
					this._D3 = value;
					this.SendPropertyChanged("D3");
					this.OnD3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D4", DbType="NVarChar(50)")]
		public string D4
		{
			get
			{
				return this._D4;
			}
			set
			{
				if ((this._D4 != value))
				{
					this.OnD4Changing(value);
					this.SendPropertyChanging();
					this._D4 = value;
					this.SendPropertyChanged("D4");
					this.OnD4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D5", DbType="NVarChar(50)")]
		public string D5
		{
			get
			{
				return this._D5;
			}
			set
			{
				if ((this._D5 != value))
				{
					this.OnD5Changing(value);
					this.SendPropertyChanging();
					this._D5 = value;
					this.SendPropertyChanged("D5");
					this.OnD5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D6", DbType="NVarChar(50)")]
		public string D6
		{
			get
			{
				return this._D6;
			}
			set
			{
				if ((this._D6 != value))
				{
					this.OnD6Changing(value);
					this.SendPropertyChanging();
					this._D6 = value;
					this.SendPropertyChanged("D6");
					this.OnD6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D7", DbType="NVarChar(50)")]
		public string D7
		{
			get
			{
				return this._D7;
			}
			set
			{
				if ((this._D7 != value))
				{
					this.OnD7Changing(value);
					this.SendPropertyChanging();
					this._D7 = value;
					this.SendPropertyChanged("D7");
					this.OnD7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D8", DbType="NVarChar(50)")]
		public string D8
		{
			get
			{
				return this._D8;
			}
			set
			{
				if ((this._D8 != value))
				{
					this.OnD8Changing(value);
					this.SendPropertyChanging();
					this._D8 = value;
					this.SendPropertyChanged("D8");
					this.OnD8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D9", DbType="NVarChar(50)")]
		public string D9
		{
			get
			{
				return this._D9;
			}
			set
			{
				if ((this._D9 != value))
				{
					this.OnD9Changing(value);
					this.SendPropertyChanging();
					this._D9 = value;
					this.SendPropertyChanged("D9");
					this.OnD9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D10", DbType="NVarChar(50)")]
		public string D10
		{
			get
			{
				return this._D10;
			}
			set
			{
				if ((this._D10 != value))
				{
					this.OnD10Changing(value);
					this.SendPropertyChanging();
					this._D10 = value;
					this.SendPropertyChanged("D10");
					this.OnD10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D11", DbType="NVarChar(50)")]
		public string D11
		{
			get
			{
				return this._D11;
			}
			set
			{
				if ((this._D11 != value))
				{
					this.OnD11Changing(value);
					this.SendPropertyChanging();
					this._D11 = value;
					this.SendPropertyChanged("D11");
					this.OnD11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D12", DbType="NVarChar(50)")]
		public string D12
		{
			get
			{
				return this._D12;
			}
			set
			{
				if ((this._D12 != value))
				{
					this.OnD12Changing(value);
					this.SendPropertyChanging();
					this._D12 = value;
					this.SendPropertyChanged("D12");
					this.OnD12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D13", DbType="NVarChar(50)")]
		public string D13
		{
			get
			{
				return this._D13;
			}
			set
			{
				if ((this._D13 != value))
				{
					this.OnD13Changing(value);
					this.SendPropertyChanging();
					this._D13 = value;
					this.SendPropertyChanged("D13");
					this.OnD13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D14", DbType="NVarChar(50)")]
		public string D14
		{
			get
			{
				return this._D14;
			}
			set
			{
				if ((this._D14 != value))
				{
					this.OnD14Changing(value);
					this.SendPropertyChanging();
					this._D14 = value;
					this.SendPropertyChanged("D14");
					this.OnD14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D15", DbType="NVarChar(50)")]
		public string D15
		{
			get
			{
				return this._D15;
			}
			set
			{
				if ((this._D15 != value))
				{
					this.OnD15Changing(value);
					this.SendPropertyChanging();
					this._D15 = value;
					this.SendPropertyChanged("D15");
					this.OnD15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D16", DbType="NVarChar(50)")]
		public string D16
		{
			get
			{
				return this._D16;
			}
			set
			{
				if ((this._D16 != value))
				{
					this.OnD16Changing(value);
					this.SendPropertyChanging();
					this._D16 = value;
					this.SendPropertyChanged("D16");
					this.OnD16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D17", DbType="NVarChar(50)")]
		public string D17
		{
			get
			{
				return this._D17;
			}
			set
			{
				if ((this._D17 != value))
				{
					this.OnD17Changing(value);
					this.SendPropertyChanging();
					this._D17 = value;
					this.SendPropertyChanged("D17");
					this.OnD17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D18", DbType="NVarChar(50)")]
		public string D18
		{
			get
			{
				return this._D18;
			}
			set
			{
				if ((this._D18 != value))
				{
					this.OnD18Changing(value);
					this.SendPropertyChanging();
					this._D18 = value;
					this.SendPropertyChanged("D18");
					this.OnD18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D19", DbType="NVarChar(50)")]
		public string D19
		{
			get
			{
				return this._D19;
			}
			set
			{
				if ((this._D19 != value))
				{
					this.OnD19Changing(value);
					this.SendPropertyChanging();
					this._D19 = value;
					this.SendPropertyChanged("D19");
					this.OnD19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D20", DbType="NVarChar(50)")]
		public string D20
		{
			get
			{
				return this._D20;
			}
			set
			{
				if ((this._D20 != value))
				{
					this.OnD20Changing(value);
					this.SendPropertyChanging();
					this._D20 = value;
					this.SendPropertyChanged("D20");
					this.OnD20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D21", DbType="NVarChar(50)")]
		public string D21
		{
			get
			{
				return this._D21;
			}
			set
			{
				if ((this._D21 != value))
				{
					this.OnD21Changing(value);
					this.SendPropertyChanging();
					this._D21 = value;
					this.SendPropertyChanged("D21");
					this.OnD21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D22", DbType="NVarChar(50)")]
		public string D22
		{
			get
			{
				return this._D22;
			}
			set
			{
				if ((this._D22 != value))
				{
					this.OnD22Changing(value);
					this.SendPropertyChanging();
					this._D22 = value;
					this.SendPropertyChanged("D22");
					this.OnD22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D23", DbType="NVarChar(50)")]
		public string D23
		{
			get
			{
				return this._D23;
			}
			set
			{
				if ((this._D23 != value))
				{
					this.OnD23Changing(value);
					this.SendPropertyChanging();
					this._D23 = value;
					this.SendPropertyChanged("D23");
					this.OnD23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D24", DbType="NVarChar(50)")]
		public string D24
		{
			get
			{
				return this._D24;
			}
			set
			{
				if ((this._D24 != value))
				{
					this.OnD24Changing(value);
					this.SendPropertyChanging();
					this._D24 = value;
					this.SendPropertyChanged("D24");
					this.OnD24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D25", DbType="NVarChar(50)")]
		public string D25
		{
			get
			{
				return this._D25;
			}
			set
			{
				if ((this._D25 != value))
				{
					this.OnD25Changing(value);
					this.SendPropertyChanging();
					this._D25 = value;
					this.SendPropertyChanged("D25");
					this.OnD25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D26", DbType="NVarChar(50)")]
		public string D26
		{
			get
			{
				return this._D26;
			}
			set
			{
				if ((this._D26 != value))
				{
					this.OnD26Changing(value);
					this.SendPropertyChanging();
					this._D26 = value;
					this.SendPropertyChanged("D26");
					this.OnD26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D27", DbType="NVarChar(50)")]
		public string D27
		{
			get
			{
				return this._D27;
			}
			set
			{
				if ((this._D27 != value))
				{
					this.OnD27Changing(value);
					this.SendPropertyChanging();
					this._D27 = value;
					this.SendPropertyChanged("D27");
					this.OnD27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D28", DbType="NVarChar(50)")]
		public string D28
		{
			get
			{
				return this._D28;
			}
			set
			{
				if ((this._D28 != value))
				{
					this.OnD28Changing(value);
					this.SendPropertyChanging();
					this._D28 = value;
					this.SendPropertyChanged("D28");
					this.OnD28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D29", DbType="NVarChar(50)")]
		public string D29
		{
			get
			{
				return this._D29;
			}
			set
			{
				if ((this._D29 != value))
				{
					this.OnD29Changing(value);
					this.SendPropertyChanging();
					this._D29 = value;
					this.SendPropertyChanged("D29");
					this.OnD29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D30", DbType="NVarChar(50)")]
		public string D30
		{
			get
			{
				return this._D30;
			}
			set
			{
				if ((this._D30 != value))
				{
					this.OnD30Changing(value);
					this.SendPropertyChanging();
					this._D30 = value;
					this.SendPropertyChanged("D30");
					this.OnD30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D31", DbType="NVarChar(50)")]
		public string D31
		{
			get
			{
				return this._D31;
			}
			set
			{
				if ((this._D31 != value))
				{
					this.OnD31Changing(value);
					this.SendPropertyChanging();
					this._D31 = value;
					this.SendPropertyChanged("D31");
					this.OnD31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChamCong_PDA", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChamCong_PDAs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChamCong_PDAs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh")]
	public partial class CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCongTrinh;
		
		private string _tenCongTrinh;
		
		private string _diaDiemXayDung;
		
		private System.Nullable<System.DateTime> _ngayCapPhep;
		
		private System.Nullable<System.DateTime> _ngayKhoiCong;
		
		private System.Nullable<System.DateTime> _ngayHoanThanh;
		
		private System.Nullable<decimal> _luongCongTrinh;
		
		private string _trangThai;
		
		private EntitySet<PhanCong> _PhanCongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCongTrinhChanging(string value);
    partial void OnmaCongTrinhChanged();
    partial void OntenCongTrinhChanging(string value);
    partial void OntenCongTrinhChanged();
    partial void OndiaDiemXayDungChanging(string value);
    partial void OndiaDiemXayDungChanged();
    partial void OnngayCapPhepChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCapPhepChanged();
    partial void OnngayKhoiCongChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKhoiCongChanged();
    partial void OnngayHoanThanhChanging(System.Nullable<System.DateTime> value);
    partial void OnngayHoanThanhChanged();
    partial void OnluongCongTrinhChanging(System.Nullable<decimal> value);
    partial void OnluongCongTrinhChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public CongTrinh()
		{
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTrinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCongTrinh
		{
			get
			{
				return this._maCongTrinh;
			}
			set
			{
				if ((this._maCongTrinh != value))
				{
					this.OnmaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._maCongTrinh = value;
					this.SendPropertyChanged("maCongTrinh");
					this.OnmaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCongTrinh", DbType="NVarChar(50)")]
		public string tenCongTrinh
		{
			get
			{
				return this._tenCongTrinh;
			}
			set
			{
				if ((this._tenCongTrinh != value))
				{
					this.OntenCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._tenCongTrinh = value;
					this.SendPropertyChanged("tenCongTrinh");
					this.OntenCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDiemXayDung", DbType="NVarChar(MAX)")]
		public string diaDiemXayDung
		{
			get
			{
				return this._diaDiemXayDung;
			}
			set
			{
				if ((this._diaDiemXayDung != value))
				{
					this.OndiaDiemXayDungChanging(value);
					this.SendPropertyChanging();
					this._diaDiemXayDung = value;
					this.SendPropertyChanged("diaDiemXayDung");
					this.OndiaDiemXayDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapPhep", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCapPhep
		{
			get
			{
				return this._ngayCapPhep;
			}
			set
			{
				if ((this._ngayCapPhep != value))
				{
					this.OnngayCapPhepChanging(value);
					this.SendPropertyChanging();
					this._ngayCapPhep = value;
					this.SendPropertyChanged("ngayCapPhep");
					this.OnngayCapPhepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKhoiCong", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayKhoiCong
		{
			get
			{
				return this._ngayKhoiCong;
			}
			set
			{
				if ((this._ngayKhoiCong != value))
				{
					this.OnngayKhoiCongChanging(value);
					this.SendPropertyChanging();
					this._ngayKhoiCong = value;
					this.SendPropertyChanged("ngayKhoiCong");
					this.OnngayKhoiCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHoanThanh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayHoanThanh
		{
			get
			{
				return this._ngayHoanThanh;
			}
			set
			{
				if ((this._ngayHoanThanh != value))
				{
					this.OnngayHoanThanhChanging(value);
					this.SendPropertyChanging();
					this._ngayHoanThanh = value;
					this.SendPropertyChanged("ngayHoanThanh");
					this.OnngayHoanThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luongCongTrinh", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> luongCongTrinh
		{
			get
			{
				return this._luongCongTrinh;
			}
			set
			{
				if ((this._luongCongTrinh != value))
				{
					this.OnluongCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._luongCongTrinh = value;
					this.SendPropertyChanged("luongCongTrinh");
					this.OnluongCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_PhanCong", Storage="_PhanCongs", ThisKey="maCongTrinh", OtherKey="maCongTrinh")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.CongTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LienHe")]
	public partial class LienHe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maLienHe;
		
		private string _email;
		
		private string _noiDung;
		
		private System.Nullable<System.DateTime> _ngayGui;
		
		private string _tpbPhanHoi;
		
		private string _trangThai;
		
		private string _maNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLienHeChanging(int value);
    partial void OnmaLienHeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnoiDungChanging(string value);
    partial void OnnoiDungChanged();
    partial void OnngayGuiChanging(System.Nullable<System.DateTime> value);
    partial void OnngayGuiChanged();
    partial void OntpbPhanHoiChanging(string value);
    partial void OntpbPhanHoiChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public LienHe()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLienHe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maLienHe
		{
			get
			{
				return this._maLienHe;
			}
			set
			{
				if ((this._maLienHe != value))
				{
					this.OnmaLienHeChanging(value);
					this.SendPropertyChanging();
					this._maLienHe = value;
					this.SendPropertyChanged("maLienHe");
					this.OnmaLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiDung", DbType="NVarChar(MAX)")]
		public string noiDung
		{
			get
			{
				return this._noiDung;
			}
			set
			{
				if ((this._noiDung != value))
				{
					this.OnnoiDungChanging(value);
					this.SendPropertyChanging();
					this._noiDung = value;
					this.SendPropertyChanged("noiDung");
					this.OnnoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayGui", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayGui
		{
			get
			{
				return this._ngayGui;
			}
			set
			{
				if ((this._ngayGui != value))
				{
					this.OnngayGuiChanging(value);
					this.SendPropertyChanging();
					this._ngayGui = value;
					this.SendPropertyChanged("ngayGui");
					this.OnngayGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpbPhanHoi", DbType="NVarChar(50)")]
		public string tpbPhanHoi
		{
			get
			{
				return this._tpbPhanHoi;
			}
			set
			{
				if ((this._tpbPhanHoi != value))
				{
					this.OntpbPhanHoiChanging(value);
					this.SendPropertyChanging();
					this._tpbPhanHoi = value;
					this.SendPropertyChanged("tpbPhanHoi");
					this.OntpbPhanHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_LienHe", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.LienHes.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.LienHes.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _hoTen;
		
		private System.Nullable<System.DateTime> _ngaySinh;
		
		private string _gioiTinh;
		
		private string _diaChiLienHe;
		
		private string _soDienThoai;
		
		private string _loaiNhanVien;
		
		private string _trangThai;
		
		private string _maPhongBan;
		
		private System.Nullable<System.DateTime> _ngayBatDau;
		
		private System.Nullable<System.DateTime> _ngayKetThuc;
		
		private EntitySet<ChamCong_PDA> _ChamCong_PDAs;
		
		private EntitySet<LienHe> _LienHes;
		
		private EntitySet<PhanCong> _PhanCongs;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
		private EntityRef<PhongBan> _PhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnngaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaySinhChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OndiaChiLienHeChanging(string value);
    partial void OndiaChiLienHeChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnloaiNhanVienChanging(string value);
    partial void OnloaiNhanVienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OnngayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBatDauChanged();
    partial void OnngayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKetThucChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChamCong_PDAs = new EntitySet<ChamCong_PDA>(new Action<ChamCong_PDA>(this.attach_ChamCong_PDAs), new Action<ChamCong_PDA>(this.detach_ChamCong_PDAs));
			this._LienHes = new EntitySet<LienHe>(new Action<LienHe>(this.attach_LienHes), new Action<LienHe>(this.detach_LienHes));
			this._PhanCongs = new EntitySet<PhanCong>(new Action<PhanCong>(this.attach_PhanCongs), new Action<PhanCong>(this.detach_PhanCongs));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			this._PhongBan = default(EntityRef<PhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(50)")]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(50)")]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiLienHe", DbType="NVarChar(300)")]
		public string diaChiLienHe
		{
			get
			{
				return this._diaChiLienHe;
			}
			set
			{
				if ((this._diaChiLienHe != value))
				{
					this.OndiaChiLienHeChanging(value);
					this.SendPropertyChanging();
					this._diaChiLienHe = value;
					this.SendPropertyChanged("diaChiLienHe");
					this.OndiaChiLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(50)")]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiNhanVien", DbType="NVarChar(50)")]
		public string loaiNhanVien
		{
			get
			{
				return this._loaiNhanVien;
			}
			set
			{
				if ((this._loaiNhanVien != value))
				{
					this.OnloaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._loaiNhanVien = value;
					this.SendPropertyChanged("loaiNhanVien");
					this.OnloaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NChar(10)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NVarChar(50)")]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					if (this._PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayBatDau
		{
			get
			{
				return this._ngayBatDau;
			}
			set
			{
				if ((this._ngayBatDau != value))
				{
					this.OnngayBatDauChanging(value);
					this.SendPropertyChanging();
					this._ngayBatDau = value;
					this.SendPropertyChanged("ngayBatDau");
					this.OnngayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChamCong_PDA", Storage="_ChamCong_PDAs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<ChamCong_PDA> ChamCong_PDAs
		{
			get
			{
				return this._ChamCong_PDAs;
			}
			set
			{
				this._ChamCong_PDAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_LienHe", Storage="_LienHes", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<LienHe> LienHes
		{
			get
			{
				return this._LienHes;
			}
			set
			{
				this._LienHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCong", Storage="_PhanCongs", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<PhanCong> PhanCongs
		{
			get
			{
				return this._PhanCongs;
			}
			set
			{
				this._PhanCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_PhongBan", ThisKey="maPhongBan", OtherKey="maPhongBan", IsForeignKey=true)]
		public PhongBan PhongBan
		{
			get
			{
				return this._PhongBan.Entity;
			}
			set
			{
				PhongBan previousValue = this._PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongBan.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._PhongBan.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maPhongBan = value.maPhongBan;
					}
					else
					{
						this._maPhongBan = default(string);
					}
					this.SendPropertyChanged("PhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChamCong_PDAs(ChamCong_PDA entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChamCong_PDAs(ChamCong_PDA entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_LienHes(LienHe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_LienHes(LienHe entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhanCongs(PhanCong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCong")]
	public partial class PhanCong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maPhanCong;
		
		private string _maNhanVien;
		
		private string _maCongTrinh;
		
		private System.Nullable<System.DateTime> _ngayBatDauLam;
		
		private System.Nullable<System.DateTime> _ngayKetThuc;
		
		private System.Nullable<int> _soNgayCong;
		
		private System.Nullable<decimal> _tienLuong;
		
		private string _trangThai;
		
		private string _daTraLuong;
		
		private EntitySet<ChamCong> _ChamCongs;
		
		private EntityRef<CongTrinh> _CongTrinh;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhanCongChanging(int value);
    partial void OnmaPhanCongChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnmaCongTrinhChanging(string value);
    partial void OnmaCongTrinhChanged();
    partial void OnngayBatDauLamChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBatDauLamChanged();
    partial void OnngayKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKetThucChanged();
    partial void OnsoNgayCongChanging(System.Nullable<int> value);
    partial void OnsoNgayCongChanged();
    partial void OntienLuongChanging(System.Nullable<decimal> value);
    partial void OntienLuongChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OndaTraLuongChanging(string value);
    partial void OndaTraLuongChanged();
    #endregion
		
		public PhanCong()
		{
			this._ChamCongs = new EntitySet<ChamCong>(new Action<ChamCong>(this.attach_ChamCongs), new Action<ChamCong>(this.detach_ChamCongs));
			this._CongTrinh = default(EntityRef<CongTrinh>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhanCong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int maPhanCong
		{
			get
			{
				return this._maPhanCong;
			}
			set
			{
				if ((this._maPhanCong != value))
				{
					this.OnmaPhanCongChanging(value);
					this.SendPropertyChanging();
					this._maPhanCong = value;
					this.SendPropertyChanged("maPhanCong");
					this.OnmaPhanCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50)")]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCongTrinh", DbType="NVarChar(50)")]
		public string maCongTrinh
		{
			get
			{
				return this._maCongTrinh;
			}
			set
			{
				if ((this._maCongTrinh != value))
				{
					if (this._CongTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._maCongTrinh = value;
					this.SendPropertyChanged("maCongTrinh");
					this.OnmaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBatDauLam", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayBatDauLam
		{
			get
			{
				return this._ngayBatDauLam;
			}
			set
			{
				if ((this._ngayBatDauLam != value))
				{
					this.OnngayBatDauLamChanging(value);
					this.SendPropertyChanging();
					this._ngayBatDauLam = value;
					this.SendPropertyChanged("ngayBatDauLam");
					this.OnngayBatDauLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soNgayCong", DbType="Int")]
		public System.Nullable<int> soNgayCong
		{
			get
			{
				return this._soNgayCong;
			}
			set
			{
				if ((this._soNgayCong != value))
				{
					this.OnsoNgayCongChanging(value);
					this.SendPropertyChanging();
					this._soNgayCong = value;
					this.SendPropertyChanged("soNgayCong");
					this.OnsoNgayCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tienLuong", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> tienLuong
		{
			get
			{
				return this._tienLuong;
			}
			set
			{
				if ((this._tienLuong != value))
				{
					this.OntienLuongChanging(value);
					this.SendPropertyChanging();
					this._tienLuong = value;
					this.SendPropertyChanged("tienLuong");
					this.OntienLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(50)")]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daTraLuong", DbType="NVarChar(50)")]
		public string daTraLuong
		{
			get
			{
				return this._daTraLuong;
			}
			set
			{
				if ((this._daTraLuong != value))
				{
					this.OndaTraLuongChanging(value);
					this.SendPropertyChanging();
					this._daTraLuong = value;
					this.SendPropertyChanged("daTraLuong");
					this.OndaTraLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhanCong_ChamCong", Storage="_ChamCongs", ThisKey="maPhanCong", OtherKey="maPhanCong")]
		public EntitySet<ChamCong> ChamCongs
		{
			get
			{
				return this._ChamCongs;
			}
			set
			{
				this._ChamCongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CongTrinh_PhanCong", Storage="_CongTrinh", ThisKey="maCongTrinh", OtherKey="maCongTrinh", IsForeignKey=true)]
		public CongTrinh CongTrinh
		{
			get
			{
				return this._CongTrinh.Entity;
			}
			set
			{
				CongTrinh previousValue = this._CongTrinh.Entity;
				if (((previousValue != value) 
							|| (this._CongTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CongTrinh.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._CongTrinh.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._maCongTrinh = value.maCongTrinh;
					}
					else
					{
						this._maCongTrinh = default(string);
					}
					this.SendPropertyChanged("CongTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCong", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhanCongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhanCongs.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChamCongs(ChamCong entity)
		{
			this.SendPropertyChanging();
			entity.PhanCong = this;
		}
		
		private void detach_ChamCongs(ChamCong entity)
		{
			this.SendPropertyChanging();
			entity.PhanCong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongBan")]
	public partial class PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhongBan;
		
		private string _tenPhongBan;
		
		private string _loaiPhongBan;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhongBanChanging(string value);
    partial void OnmaPhongBanChanged();
    partial void OntenPhongBanChanging(string value);
    partial void OntenPhongBanChanged();
    partial void OnloaiPhongBanChanging(string value);
    partial void OnloaiPhongBanChanged();
    #endregion
		
		public PhongBan()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhongBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhongBan
		{
			get
			{
				return this._maPhongBan;
			}
			set
			{
				if ((this._maPhongBan != value))
				{
					this.OnmaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._maPhongBan = value;
					this.SendPropertyChanged("maPhongBan");
					this.OnmaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPhongBan", DbType="NVarChar(30)")]
		public string tenPhongBan
		{
			get
			{
				return this._tenPhongBan;
			}
			set
			{
				if ((this._tenPhongBan != value))
				{
					this.OntenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._tenPhongBan = value;
					this.SendPropertyChanged("tenPhongBan");
					this.OntenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiPhongBan", DbType="NVarChar(50)")]
		public string loaiPhongBan
		{
			get
			{
				return this._loaiPhongBan;
			}
			set
			{
				if ((this._loaiPhongBan != value))
				{
					this.OnloaiPhongBanChanging(value);
					this.SendPropertyChanging();
					this._loaiPhongBan = value;
					this.SendPropertyChanged("loaiPhongBan");
					this.OnloaiPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongBan_NhanVien", Storage="_NhanViens", ThisKey="maPhongBan", OtherKey="maPhongBan")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.PhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenTaiKhoan;
		
		private string _matKhau;
		
		private string _maNhanVien;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenTaiKhoanChanging(string value);
    partial void OntenTaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenTaiKhoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenTaiKhoan
		{
			get
			{
				return this._tenTaiKhoan;
			}
			set
			{
				if ((this._tenTaiKhoan != value))
				{
					this.OntenTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._tenTaiKhoan = value;
					this.SendPropertyChanged("tenTaiKhoan");
					this.OntenTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="VarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
